# Generated by Django 3.2.6 on 2021-08-24 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='id',
        ),
        migrations.AlterField(
            model_name='history',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
