# Generated by Django 3.2.6 on 2021-08-24 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20210824_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
