# Generated by Django 3.2.6 on 2021-08-12 16:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_auto_20210811_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebook',
            options={'ordering': ['title', '-timestamp']},
        ),
        migrations.RemoveField(
            model_name='note',
            name='notebook',
        ),
        migrations.CreateModel(
            name='NotebookTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('a', 'yellow'), ('b', 'white'), ('c', 'green'), ('d', 'red'), ('e', 'blue')], default='a', max_length=1)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.notebook')),
            ],
            options={
                'ordering': ['-title', '-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='notebooktab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notebook.notebooktab'),
            preserve_default=False,
        ),
    ]
