# Generated by Django 3.2.6 on 2021-08-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_auto_20210812_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebooktab',
            options={'ordering': ['notebook_id']},
        ),
        migrations.AlterField(
            model_name='notebooktab',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='notebook.notebook'),
        ),
    ]
