# Generated by Django 3.2.6 on 2021-08-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0008_notebookpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebookpage',
            options={'ordering': ['notebook_tab_id']},
        ),
    ]
