# Generated by Django 3.2.6 on 2021-08-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0009_alter_notebookpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='note',
            name='pinned',
        ),
    ]
