# Generated by Django 3.2.6 on 2021-08-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0013_auto_20210818_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='indent',
            field=models.SmallIntegerField(default=4, editable=False),
        ),
    ]
