# Generated by Django 3.2.6 on 2021-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0014_alter_note_indent'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='version',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('id', 'version')},
        ),
    ]
