# Generated by Django 3.2.6 on 2021-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0015_auto_20210824_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
